controllers:
    config:
        body:
            cascaded_position: False
            dynamic_reconfigure: True
        joints:
            cascaded_position: False
            dynamic_reconfigure: True
    fwd_left:
        velocity: {p: 20, i: 1, d: 0.0}
        position: {p: 1, i: 0.1, d: 0.5}
    fwd_right:
        velocity: {p: 20, i: 1, d: 0.0}
        position: {p: 1, i: 0.1, d: 0.5}
    # no PID gains for body x,y,z,roll,pitch,yaw -> control at the thruster level
